
;; -- Header ------------------------------------------------------------------
;; ----------------------------------------------------------------------------

; Author: bithandshake
; Created: 2021.01.01
; Description:
; Version: v0.6.0
; Compatibility: x4.5.8



;; -- Namespace ---------------------------------------------------------------
;; ----------------------------------------------------------------------------

(ns x.server-environment.crawler-handler
    (:require [mid-fruits.candy   :refer [param return]]
              [mid-fruits.time    :as time]
              [mid-fruits.uri     :as uri]
              [server-fruits.http :as http]
              [x.app-details      :as details]
              [x.server-core.api  :as a]
              [x.server-user.api  :as user]))



;; ----------------------------------------------------------------------------
;; ----------------------------------------------------------------------------

(defn- robots-txt
  ; WARNING! NON-PUBLIC! DO NOT USE!
  ;
  ; @param (string) app-home
  ;
  ; @return (string)
  [app-home]
  (let [app-home  (uri/valid-path app-home)
        timestamp (time/timestamp-string)]
       (str "\n# Generated by: " details/app-codename
            "\n# Generated at: " timestamp "\n"
            "\nUser-agent: *\nAllow: /\nDisallow: " app-home "\n")))

(defn download-robots-txt
  ; WARNING! NON-PUBLIC! DO NOT USE!
  ;
  ; @param (map) request
  ;
  ; @return (map)
  ;  {:body (string)}
  [_]
  (let [app-home   (a/subscribed [:core/get-app-config-item :app-home])
        robots-txt (robots-txt app-home)]
       (http/text-wrap {:body robots-txt})))



;; ----------------------------------------------------------------------------
;; ----------------------------------------------------------------------------

(defn crawler-rules
  ; WARNING! NON-PUBLIC! DO NOT USE!
  ;
  ; A <meta name="robots"> tag content attribútumának értéke
  ;
  ; index:   Show this page in search results
  ; follow:  Follow the links on this page
  ; archive: Show a cached link in search results
  ; snippet: Show a text snippet or video preview in the search results for this page
  ;
  ; @param (map) request
  ;
  ; @return (string)
  [request]
  (if (user/request->authenticated? request)
      (return "noindex, nofollow, noarchive, nosnippet")
      (return "index, follow, noarchive, max-snippet:200, max-image-preview:large")))
